# Generated by Django 4.0.3 on 2022-04-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('nombre_usuario', models.CharField(max_length=20)),
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('posteo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('nombre_usuario', models.CharField(max_length=20)),
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('sub_titulo', models.CharField(max_length=50)),
                ('posteo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=20)),
            ],
        ),
    ]
